### ISSUE TITLE
Reserved word "class" causing JS errors in some browsers

### ISSUE THREAD

**Issue by loudin** [jgallen23/clientjade#2]
Hey there,

First off, great library! Lightweight and exactly what I needed. However, there's a bug in your exports.merge function. In the current form it's written as:

exports.merge = function merge(a, b) {
  var ac = a.class;
  var bc = b.class;

  if (ac || bc) {
    ac = ac || [];
    bc = bc || [];
    if (!Array.isArray(ac)) ac = [ac];
    if (!Array.isArray(bc)) bc = [bc];
    ac = ac.filter(nulls);
    bc = bc.filter(nulls);
    a.class = ac.concat(bc).join(' ');
  }

  for (var key in b) {
    if ('class' == key) continue;
    a[key] = b[key];
  }

  return a;
};

You cannot use the .class notation because "class" is a reserved word in javascript. Some web browsers have no problem parsing this, but others do (confirmed on Mobile Safari). If you fix the notation to read:

var ac = a["class"];
var bc = b["class"];
....
a["class"] = ac.concat(bc).join(' ');

It'll compile correctly. Would definitely try to help myself, but I don't have access to the source. Right now, my only fix is to manually edit the code after each time I compile.

**Comment by jgallen23** [comment]
just pushed up a new version, give that a try

**Comment by loudin** [comment]
Works great, thanks!
