### ISSUE TITLE
Higher Performance Render

### ISSUE THREAD

**Issue by ghost** [jgallen23/clientjade#4]
Hey, I love this library; wish it was more popular. Anyway, I thought I'd let you know that there's a higher-performance tweak to innerHTML that only requires a few line changes. Credit goes to this old article: http://blog.stevenlevithan.com/archives/faster-than-innerhtml

`lib/browser/render.js`

``` javascript
jade.templates = {};
jade.render = function(node, template, data) {
  var newEl = node.cloneNode(false), //False means non-deep clone
      parent = node.parentNode,
      tmp = jade.templates[template](data);

  newEl.innerHTML = tmp(data);
  if (parent) parent.replaceChild(newEl, node);

  return newEl;
};
```

**Comment by jgallen23** [comment]
clientjade just uses the runtime from the jade library.  You should post this here: https://github.com/visionmedia/jade

Thanks
