### ISSUE TITLE
Create an toHtml function like jade.toHtml.

### ISSUE THREAD

**Issue by tinganho** [jgallen23/clientjade#5]
Not everyone like to render always. It would be good fi there where toHtml function

**Comment by nlfurniss** [comment]
This would be useful, any chance of @tinganho PR getting merged?

**Comment by brianblocker** [comment]
Will get something like this merged in soon, @tinganho's PR is currently closed pending changes. Will leave this open until we get this done.

**Comment by brianblocker** [comment]
On 2nd thought, this isn't an "issue" technically, so going to close this. Definitely in the pipeline though!
